[context.production.environment]
VITE_APP_API_URI = "https://arozec-prod.herokuapp.com/"

    [context.branch-deploy.environment]
    VITE_APP_API_URI = "https://arozec-staging.herokuapp.com/"

        [context.staging.environment]
        VITE_APP_API_URI = "https://arozec-staging.herokuapp.com/"
